/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interview;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
class RegistryTest {

    @Test void test1() {
        assertNotNull(null, "expected to fail");
    }
}
